--------------------------------------------------------
--  Fichier créé - mardi-septembre-22-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TRAVAIL
--------------------------------------------------------

  CREATE TABLE TRAVAIL 
   (	NUEMPL NUMBER(4,0), 
	NUPROJ NUMBER(3,0), 
	DUREE NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
REM INSERTING into TRAVAIL
SET DEFINE OFF;
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('20','492','10');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('23','237','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('23','135','10');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('37','160','30');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('39','237','10');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('39','135','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('41','103','20');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('41','492','20');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('42','135','30');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('48','492','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('48','160','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('51','160','20');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('52','492','10');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('52','135','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('57','103','20');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('57','370','10');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('57','135','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('14','492','20');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('14','160','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('28','135','10');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('28','160','10');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('30','103','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('30','237','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('30','370','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('30','135','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('30','160','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('30','492','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('62','492','25');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('68','370','25');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('71','237','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('71','492','20');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('71','370','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('19','237','10');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('19','160','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('65','370','5');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('65','160','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('73','370','15');
Insert into TRAVAIL (NUEMPL,NUPROJ,DUREE) values ('73','492','15');
--------------------------------------------------------
--  DDL for Index PK_TRAVAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX PK_TRAVAIL ON TRAVAIL (NUEMPL, NUPROJ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS ;
--------------------------------------------------------
--  Constraints for Table TRAVAIL
--------------------------------------------------------

  ALTER TABLE TRAVAIL ADD CONSTRAINT PK_TRAVAIL PRIMARY KEY (NUEMPL, NUPROJ)
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE USERS  ENABLE;
  ALTER TABLE TRAVAIL MODIFY (DUREE NOT NULL ENABLE);
  ALTER TABLE TRAVAIL MODIFY (NUPROJ NOT NULL ENABLE);
  ALTER TABLE TRAVAIL MODIFY (NUEMPL NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table TRAVAIL
--------------------------------------------------------

  ALTER TABLE TRAVAIL ADD CONSTRAINT FK_TRAVAILEMPLOYE FOREIGN KEY (NUEMPL)
	  REFERENCES EMPLOYE (NUEMPL) ENABLE;
  ALTER TABLE TRAVAIL ADD CONSTRAINT FK_TRAVAILPROJET FOREIGN KEY (NUPROJ)
	  REFERENCES PROJET (NUPROJ) ENABLE;
