--------------------------------------------------------
--  Fichier créé - mardi-septembre-22-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CONCERNE
--------------------------------------------------------

  CREATE TABLE "S3A02A"."CONCERNE" 
   (	"NUSERV" NUMBER(2,0), 
	"NUPROJ" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into S3A02A.CONCERNE
SET DEFINE OFF;
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('1','103');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('1','135');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('1','370');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('2','103');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('2','160');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('2','237');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('2','370');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('2','492');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('3','135');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('3','237');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('3','370');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('3','492');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('4','103');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('4','135');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('4','160');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('4','370');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('4','492');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('5','160');
Insert into S3A02A.CONCERNE (NUSERV,NUPROJ) values ('5','370');
--------------------------------------------------------
--  DDL for Index PK_CONCERNE
--------------------------------------------------------

  CREATE UNIQUE INDEX "S3A02A"."PK_CONCERNE" ON "S3A02A"."CONCERNE" ("NUSERV", "NUPROJ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CONCERNE
--------------------------------------------------------

  ALTER TABLE "S3A02A"."CONCERNE" ADD CONSTRAINT "PK_CONCERNE" PRIMARY KEY ("NUSERV", "NUPROJ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "S3A02A"."CONCERNE" MODIFY ("NUPROJ" NOT NULL ENABLE);
  ALTER TABLE "S3A02A"."CONCERNE" MODIFY ("NUSERV" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CONCERNE
--------------------------------------------------------

  ALTER TABLE "S3A02A"."CONCERNE" ADD CONSTRAINT "FK_CONCERNEPROJET" FOREIGN KEY ("NUPROJ")
	  REFERENCES "S3A02A"."PROJET" ("NUPROJ") ENABLE;
  ALTER TABLE "S3A02A"."CONCERNE" ADD CONSTRAINT "FK_CONCERNESERV" FOREIGN KEY ("NUSERV")
	  REFERENCES "S3A02A"."SERVICE" ("NUSERV") ENABLE;
